import * as esbuild from "esbuild";
import { builtinModules } from "node:module";
import { copyFile, mkdir, rm, writeFile, watch } from "node:fs/promises";
import { buildStyles, inlineExcalidrawFonts } from "./scripts/build-assets.mjs";
import { bundledNotices } from "./scripts/build-notices.mjs";

const production = process.argv.includes("production");
await buildStyles();
const context = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  format: "cjs",
  platform: "browser",
  target: "es2021",
  conditions: [production ? "production" : "development"],
  external: ["obsidian", "electron", ...builtinModules],
  define: { "process.env.NODE_ENV": JSON.stringify(production ? "production" : "development") },
  plugins: [inlineExcalidrawFonts, bundledNotices],
  loader: { ".woff2": "dataurl" },
  outfile: "main.js",
  sourcemap: production ? false : "inline",
  minify: production,
  metafile: true,
  logLevel: "info",
  banner: { js: "/* Mermaid Excalidraw Renderer — generated by esbuild. */" },
});

if (production) {
  try {
    const result = await context.rebuild();
    await rm("dist/mermaid-excalidraw-renderer", { recursive: true, force: true });
    await mkdir("dist/mermaid-excalidraw-renderer", { recursive: true });
    await writeFile("dist/build-meta.json", JSON.stringify(result.metafile, null, 2));
    for (const file of ["main.js", "manifest.json", "styles.css", "THIRD_PARTY_NOTICES.txt", "LICENSE"]) {
      await copyFile(file, `dist/mermaid-excalidraw-renderer/${file}`);
    }
  } finally { await context.dispose(); }
} else {
  await context.watch();
  console.log("Watching TypeScript and src/styles.css…");
  const controller = new AbortController();
  process.once("SIGINT", () => controller.abort());
  process.once("SIGTERM", () => controller.abort());
  try {
    for await (const event of watch("src/styles.css", { signal: controller.signal })) {
      if (event.eventType === "change") await buildStyles();
    }
  } catch (error) {
    if (!controller.signal.aborted) throw error;
  } finally { await context.dispose(); }
}
